apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: <ENTER HERE YOUR APP NAME>
  namespace: <ENTER HERE YOURPROCESSING NAMESPACE>
spec:
  timeToLiveSeconds: 3600
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: <ENTER HERE YOUR IMAGE TAG>
  imagePullPolicy: Always
  mainApplicationFile: <ENTER HERE YOUR PYTHON SCRIPT PATH>
  sparkVersion: 3.2.2
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreRequest: 250m
    coreLimit: 500m
    memory: 3G
    labels:
      version: 3.2.2
  executor:
    cores: 8
    instances: 1
    coreRequest: 1000m
    coreLimit: 1000m
    memory: 3G
    labels:
      version: 3.2.2